name: Auto Fix Issues

on:
  issues:
    types: [labeled]

jobs:
  trigger-agent:
    if: github.event.label.name == 'auto-fix'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: read
    steps:
      - name: Checkout target repository (repo 2)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target-repo

      - name: Checkout bug-fix-agent (repo 1)
        uses: actions/checkout@v4
        with:
          repository: k4han/bug-fix-agent
          token: ${{ secrets.PAT_PRIVATE_REPO }}
          path: bug-fix-agent
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        working-directory: bug-fix-agent
        run: uv venv

      - name: Install dependencies
        working-directory: bug-fix-agent
        run: uv sync

      - name: Run bug fix agent
        working-directory: target-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PATH: ${{ github.workspace }}/bug-fix-agent/.venv/bin:$PATH
        run: ../bug-fix-agent/.venv/bin/python ../bug-fix-agent/agent/main.py
