name: Auto Fix Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  trigger-agent:
    if: contains(github.event.issue.labels.*.name, 'auto-fix')
    uses: k4han/bug-fix-agent/.github/workflows/fix-bug-reusable.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      issue_title: ${{ github.event.issue.title }}
      issue_body: ${{ github.event.issue.body }}
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
