name: Auto Fix Issues

on:
  issues:
    types: [labeled]

jobs:
  trigger-agent:
    if: github.event.label.name == 'auto-fix'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository (repo 2)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target-repo

      - name: Checkout bug-fix-agent (repo 1)
        uses: actions/checkout@v4
        with:
          repository: k4han/bug-fix-agent
          token: ${{ secrets.PAT_PRIVATE_REPO }}
          path: bug-fix-agent
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r bug-fix-agent/requirements.txt

      - name: Run bug fix agent
        working-directory: target-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python ../bug-fix-agent/agent/main.py
